# Project-specific AEM configuration

# Inherit default AEM functionality from "AEM Definitions", see http://devops.wcm.io/conga/definitions/aem/
inherits:
- role: aem-cms

variants:
- variant: aem-author
- variant: aem-publish

templateDir: to.adapt.xwalk.components-aem-cms

files:


# Application bundles and packages
- url: mvn:to.adapt.xwalk/to.adapt.xwalk.components.core
  dir: bundles
- url: mvn:to.adapt.xwalk/to.adapt.xwalk.components.ui.apps//zip
  dir: packages


# Defines configuration parameters and default values
config:
  contentPackage:
    group: adaptto-xwalk
    version: ${version}
